/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
* other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
* EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
* SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS
* SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
* this software. By using this software, you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2019-2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "profile_cmn/r_ble_serv_common.h"

extern st_ble_gatts_db_cfg_t g_gatt_db_table;

typedef enum
{
    BLE_INVALID_ATTR_HDL = 0x0000,
    BLE_GAPS_DECL_HDL = 0x0001,
    BLE_GAPS_DEV_NAME_DECL_HDL = 0x0002,
    BLE_GAPS_DEV_NAME_VAL_HDL = 0x0003,
    BLE_GAPS_APPEARANCE_DECL_HDL = 0x0004,
    BLE_GAPS_APPEARANCE_VAL_HDL = 0x0005,
    BLE_GAPS_PER_PREF_CONN_PARAM_DECL_HDL = 0x0006,
    BLE_GAPS_PER_PREF_CONN_PARAM_VAL_HDL = 0x0007,
    BLE_GAPS_CENT_ADDR_RSLV_DECL_HDL = 0x0008,
    BLE_GAPS_CENT_ADDR_RSLV_VAL_HDL = 0x0009,
    BLE_GAPS_RSLV_PRIV_ADDR_ONLY_DECL_HDL = 0x000A,
    BLE_GAPS_RSLV_PRIV_ADDR_ONLY_VAL_HDL = 0x000B,
    BLE_GATS_DECL_HDL = 0x000C,
    BLE_GATS_SERV_CHGED_DECL_HDL = 0x000D,
    BLE_GATS_SERV_CHGED_VAL_HDL = 0x000E,
    BLE_GATS_SERV_CHGED_CLI_CNFG_DESC_HDL = 0x000F,
    BLE_LSS_DECL_HDL = 0x0010,
    BLE_LSS_SWITCH_STATE_DECL_HDL = 0x0011,
    BLE_LSS_SWITCH_STATE_VAL_HDL = 0x0012,
    BLE_LSS_SWITCH_STATE_CLI_CNFG_DESC_HDL = 0x0013,
    BLE_LSS_BLINK_RATE_DECL_HDL = 0x0014,
    BLE_LSS_BLINK_RATE_VAL_HDL = 0x0015,
    BLE_UDS_DECL_HDL = 0x0016,
    BLE_UDS_FIRST_NAME_DECL_HDL = 0x0017,
    BLE_UDS_FIRST_NAME_VAL_HDL = 0x0018,
    BLE_UDS_LAST_NAME_DECL_HDL = 0x0019,
    BLE_UDS_LAST_NAME_VAL_HDL = 0x001A,
    BLE_UDS_EMAIL_ADDR_DECL_HDL = 0x001B,
    BLE_UDS_EMAIL_ADDR_VAL_HDL = 0x001C,
    BLE_UDS_AGE_DECL_HDL = 0x001D,
    BLE_UDS_AGE_VAL_HDL = 0x001E,
    BLE_UDS_DATE_OF_BIRTH_DECL_HDL = 0x001F,
    BLE_UDS_DATE_OF_BIRTH_VAL_HDL = 0x0020,
    BLE_UDS_GENDER_DECL_HDL = 0x0021,
    BLE_UDS_GENDER_VAL_HDL = 0x0022,
    BLE_UDS_WEIGHT_DECL_HDL = 0x0023,
    BLE_UDS_WEIGHT_VAL_HDL = 0x0024,
    BLE_UDS_HEIGHT_DECL_HDL = 0x0025,
    BLE_UDS_HEIGHT_VAL_HDL = 0x0026,
    BLE_UDS_VO2_MAX_DECL_HDL = 0x0027,
    BLE_UDS_VO2_MAX_VAL_HDL = 0x0028,
    BLE_UDS_HEART_RATE_MAX_DECL_HDL = 0x0029,
    BLE_UDS_HEART_RATE_MAX_VAL_HDL = 0x002A,
    BLE_UDS_RESTING_HEART_RATE_DECL_HDL = 0x002B,
    BLE_UDS_RESTING_HEART_RATE_VAL_HDL = 0x002C,
    BLE_UDS_MAX_RECOMMENDED_HEART_RATE_DECL_HDL = 0x002D,
    BLE_UDS_MAX_RECOMMENDED_HEART_RATE_VAL_HDL = 0x002E,
    BLE_UDS_AEROBIC_THRESHOLD_DECL_HDL = 0x002F,
    BLE_UDS_AEROBIC_THRESHOLD_VAL_HDL = 0x0030,
    BLE_UDS_ANAEROBIC_THRESHOLD_DECL_HDL = 0x0031,
    BLE_UDS_ANAEROBIC_THRESHOLD_VAL_HDL = 0x0032,
    BLE_UDS_SPORT_TYPE_FOR_THRESHOLD_DECL_HDL = 0x0033,
    BLE_UDS_SPORT_TYPE_FOR_THRESHOLD_VAL_HDL = 0x0034,
    BLE_UDS_DATE_OF_THRESHOLD_ASSESSMENT_DECL_HDL = 0x0035,
    BLE_UDS_DATE_OF_THRESHOLD_ASSESSMENT_VAL_HDL = 0x0036,
    BLE_UDS_WAIST_CIRCUMFERENCE_DECL_HDL = 0x0037,
    BLE_UDS_WAIST_CIRCUMFERENCE_VAL_HDL = 0x0038,
    BLE_UDS_HIP_CIRCUMFERENCE_DECL_HDL = 0x0039,
    BLE_UDS_HIP_CIRCUMFERENCE_VAL_HDL = 0x003A,
    BLE_UDS_FAT_BURN_HEART_RATE_LOWER_LIMIT_DECL_HDL = 0x003B,
    BLE_UDS_FAT_BURN_HEART_RATE_LOWER_LIMIT_VAL_HDL = 0x003C,
    BLE_UDS_FAT_BURN_HEART_RATE_UPPER_LIMIT_DECL_HDL = 0x003D,
    BLE_UDS_FAT_BURN_HEART_RATE_UPPER_LIMIT_VAL_HDL = 0x003E,
    BLE_UDS_AEROBIC_HEART_RATE_LOWER_LIMIT_DECL_HDL = 0x003F,
    BLE_UDS_AEROBIC_HEART_RATE_LOWER_LIMIT_VAL_HDL = 0x0040,
    BLE_UDS_AEROBIC_HEART_RATE_UPPER_LIMIT_DECL_HDL = 0x0041,
    BLE_UDS_AEROBIC_HEART_RATE_UPPER_LIMIT_VAL_HDL = 0x0042,
    BLE_UDS_ANAEROBIC_HEART_RATE_LOWER_LIMIT_DECL_HDL = 0x0043,
    BLE_UDS_ANAEROBIC_HEART_RATE_LOWER_LIMIT_VAL_HDL = 0x0044,
    BLE_UDS_ANAEROBIC_HEART_RATE_UPPER_LIMIT_DECL_HDL = 0x0045,
    BLE_UDS_ANAEROBIC_HEART_RATE_UPPER_LIMIT_VAL_HDL = 0x0046,
    BLE_UDS_FIVE_ZONE_HEART_RATE_LIMITS_DECL_HDL = 0x0047,
    BLE_UDS_FIVE_ZONE_HEART_RATE_LIMITS_VAL_HDL = 0x0048,
    BLE_UDS_THREE_ZONE_HEART_RATE_LIMITS_DECL_HDL = 0x0049,
    BLE_UDS_THREE_ZONE_HEART_RATE_LIMITS_VAL_HDL = 0x004A,
    BLE_UDS_TWO_ZONE_HEART_RATE_LIMIT_DECL_HDL = 0x004B,
    BLE_UDS_TWO_ZONE_HEART_RATE_LIMIT_VAL_HDL = 0x004C,
    BLE_UDS_DB_CHANGE_INCREMENT_DECL_HDL = 0x004D,
    BLE_UDS_DB_CHANGE_INCREMENT_VAL_HDL = 0x004E,
    BLE_UDS_DB_CHANGE_INCREMENT_CLI_CNFG_DESC_HDL = 0x004F,
    BLE_UDS_USER_INDEX_DECL_HDL = 0x0050,
    BLE_UDS_USER_INDEX_VAL_HDL = 0x0051,
    BLE_UDS_USER_CNTRL_PNT_DECL_HDL = 0x0052,
    BLE_UDS_USER_CNTRL_PNT_VAL_HDL = 0x0053,
    BLE_UDS_USER_CNTRL_PNT_CLI_CNFG_DESC_HDL = 0x0054,
    BLE_UDS_LANGUAGE_DECL_HDL = 0x0055,
    BLE_UDS_LANGUAGE_VAL_HDL = 0x0056,
    BLE_HRS_DECL_HDL = 0x0057,
    BLE_HRS_MEAS_DECL_HDL = 0x0058,
    BLE_HRS_MEAS_VAL_HDL = 0x0059,
    BLE_HRS_MEAS_CLI_CNFG_DESC_HDL = 0x005A,
    BLE_HRS_BODY_SENSOR_LOCATION_DECL_HDL = 0x005B,
    BLE_HRS_BODY_SENSOR_LOCATION_VAL_HDL = 0x005C,
    BLE_HRS_HEART_RATE_CP_DECL_HDL = 0x005D,
    BLE_HRS_HEART_RATE_CP_VAL_HDL = 0x005E,
    BLE_DIS_DECL_HDL = 0x005F,
    BLE_DIS_MFR_NAME_DECL_HDL = 0x0060,
    BLE_DIS_MFR_NAME_VAL_HDL = 0x0061,
    BLE_DIS_MODEL_NUM_DECL_HDL = 0x0062,
    BLE_DIS_MODEL_NUM_VAL_HDL = 0x0063,
    BLE_DIS_SER_NUM_DECL_HDL = 0x0064,
    BLE_DIS_SER_NUM_VAL_HDL = 0x0065,
    BLE_DIS_HW_REV_DECL_HDL = 0x0066,
    BLE_DIS_HW_REV_VAL_HDL = 0x0067,
    BLE_DIS_FIRM_REV_DECL_HDL = 0x0068,
    BLE_DIS_FIRM_REV_VAL_HDL = 0x0069,
    BLE_DIS_SW_REV_DECL_HDL = 0x006A,
    BLE_DIS_SW_REV_VAL_HDL = 0x006B,
    BLE_DIS_SYS_ID_DECL_HDL = 0x006C,
    BLE_DIS_SYS_ID_VAL_HDL = 0x006D,
    BLE_DIS_REG_CER_DATA_LIST_DECL_HDL = 0x006E,
    BLE_DIS_REG_CER_DATA_LIST_VAL_HDL = 0x006F,
    BLE_DIS_PNP_ID_DECL_HDL = 0x0070,
    BLE_DIS_PNP_ID_VAL_HDL = 0x0071,
    BLE_OTS_DECL_HDL = 0x0072,
    BLE_OTS_FEAT_DECL_HDL = 0x0073,
    BLE_OTS_FEAT_VAL_HDL = 0x0074,
    BLE_OTS_OBJ_NAME_DECL_HDL = 0x0075,
    BLE_OTS_OBJ_NAME_VAL_HDL = 0x0076,
    BLE_OTS_OBJ_TYPE_DECL_HDL = 0x0077,
    BLE_OTS_OBJ_TYPE_VAL_HDL = 0x0078,
    BLE_OTS_OBJ_SIZE_DECL_HDL = 0x0079,
    BLE_OTS_OBJ_SIZE_VAL_HDL = 0x007A,
    BLE_OTS_OBJ_FIRST_CREATED_DECL_HDL = 0x007B,
    BLE_OTS_OBJ_FIRST_CREATED_VAL_HDL = 0x007C,
    BLE_OTS_OBJ_LAST_MODIFIED_DECL_HDL = 0x007D,
    BLE_OTS_OBJ_LAST_MODIFIED_VAL_HDL = 0x007E,
    BLE_OTS_OBJ_ID_DECL_HDL = 0x007F,
    BLE_OTS_OBJ_ID_VAL_HDL = 0x0080,
    BLE_OTS_OBJ_PROP_DECL_HDL = 0x0081,
    BLE_OTS_OBJ_PROP_VAL_HDL = 0x0082,
    BLE_OTS_OBJ_ACTION_CP_DECL_HDL = 0x0083,
    BLE_OTS_OBJ_ACTION_CP_VAL_HDL = 0x0084,
    BLE_OTS_OBJ_ACTION_CP_CLI_CNFG_DESC_HDL = 0x0085,
    BLE_OTS_OBJ_LIST_CP_DECL_HDL = 0x0086,
    BLE_OTS_OBJ_LIST_CP_VAL_HDL = 0x0087,
    BLE_OTS_OBJ_LIST_CP_CLI_CNFG_DESC_HDL = 0x0088,
    BLE_OTS_OBJ_LIST_FILTER_0_DECL_HDL = 0x0089,
    BLE_OTS_OBJ_LIST_FILTER_0_VAL_HDL = 0x008A,
    BLE_OTS_OBJ_LIST_FILTER_1_DECL_HDL = 0x008B,
    BLE_OTS_OBJ_LIST_FILTER_1_VAL_HDL = 0x008C,
    BLE_OTS_OBJ_LIST_FILTER_2_DECL_HDL = 0x008D,
    BLE_OTS_OBJ_LIST_FILTER_2_VAL_HDL = 0x008E,
    BLE_OTS_OBJ_CHANGED_DECL_HDL = 0x008F,
    BLE_OTS_OBJ_CHANGED_VAL_HDL = 0x0090,
    BLE_OTS_OBJ_CHANGED_CLI_CNFG_DESC_HDL = 0x0091,
} e_ble_attr_hdl_t;

#define BLE_GAPS_DEV_NAME_LEN (128)
#define BLE_GAPS_APPEARANCE_LEN (2)
#define BLE_GAPS_PER_PREF_CONN_PARAM_LEN (8)
#define BLE_GAPS_CENT_ADDR_RSLV_LEN (1)
#define BLE_GAPS_RSLV_PRIV_ADDR_ONLY_LEN (1)
#define BLE_GATS_SERV_CHGED_LEN (4)
#define BLE_GATS_SERV_CHGED_CLI_CNFG_LEN (2)
#define BLE_LSS_SWITCH_STATE_LEN (1)
#define BLE_LSS_SWITCH_STATE_CLI_CNFG_LEN (2)
#define BLE_LSS_BLINK_RATE_LEN (1)
#define BLE_UDS_FIRST_NAME_LEN (100)
#define BLE_UDS_LAST_NAME_LEN (100)
#define BLE_UDS_EMAIL_ADDR_LEN (100)
#define BLE_UDS_AGE_LEN (1)
#define BLE_UDS_DATE_OF_BIRTH_LEN (4)
#define BLE_UDS_GENDER_LEN (1)
#define BLE_UDS_WEIGHT_LEN (2)
#define BLE_UDS_HEIGHT_LEN (2)
#define BLE_UDS_VO2_MAX_LEN (1)
#define BLE_UDS_HEART_RATE_MAX_LEN (1)
#define BLE_UDS_RESTING_HEART_RATE_LEN (1)
#define BLE_UDS_MAX_RECOMMENDED_HEART_RATE_LEN (1)
#define BLE_UDS_AEROBIC_THRESHOLD_LEN (1)
#define BLE_UDS_ANAEROBIC_THRESHOLD_LEN (1)
#define BLE_UDS_SPORT_TYPE_FOR_THRESHOLD_LEN (1)
#define BLE_UDS_DATE_OF_THRESHOLD_ASSESSMENT_LEN (4)
#define BLE_UDS_WAIST_CIRCUMFERENCE_LEN (2)
#define BLE_UDS_HIP_CIRCUMFERENCE_LEN (2)
#define BLE_UDS_FAT_BURN_HEART_RATE_LOWER_LIMIT_LEN (1)
#define BLE_UDS_FAT_BURN_HEART_RATE_UPPER_LIMIT_LEN (1)
#define BLE_UDS_AEROBIC_HEART_RATE_LOWER_LIMIT_LEN (1)
#define BLE_UDS_AEROBIC_HEART_RATE_UPPER_LIMIT_LEN (1)
#define BLE_UDS_ANAEROBIC_HEART_RATE_LOWER_LIMIT_LEN (1)
#define BLE_UDS_ANAEROBIC_HEART_RATE_UPPER_LIMIT_LEN (1)
#define BLE_UDS_FIVE_ZONE_HEART_RATE_LIMITS_LEN (4)
#define BLE_UDS_THREE_ZONE_HEART_RATE_LIMITS_LEN (2)
#define BLE_UDS_TWO_ZONE_HEART_RATE_LIMIT_LEN (1)
#define BLE_UDS_DB_CHANGE_INCREMENT_LEN (4)
#define BLE_UDS_DB_CHANGE_INCREMENT_CLI_CNFG_LEN (2)
#define BLE_UDS_USER_INDEX_LEN (1)
#define BLE_UDS_USER_CNTRL_PNT_LEN (20)
#define BLE_UDS_USER_CNTRL_PNT_CLI_CNFG_LEN (2)
#define BLE_UDS_LANGUAGE_LEN (100)
#define BLE_HRS_MEAS_LEN (20)
#define BLE_HRS_MEAS_CLI_CNFG_LEN (2)
#define BLE_HRS_BODY_SENSOR_LOCATION_LEN (1)
#define BLE_HRS_HEART_RATE_CP_LEN (1)
#define BLE_DIS_MFR_NAME_LEN (100)
#define BLE_DIS_MODEL_NUM_LEN (100)
#define BLE_DIS_SER_NUM_LEN (100)
#define BLE_DIS_HW_REV_LEN (100)
#define BLE_DIS_FIRM_REV_LEN (100)
#define BLE_DIS_SW_REV_LEN (100)
#define BLE_DIS_SYS_ID_LEN (8)
#define BLE_DIS_REG_CER_DATA_LIST_LEN (100)
#define BLE_DIS_PNP_ID_LEN (7)
#define BLE_OTS_FEAT_LEN (8)
#define BLE_OTS_OBJ_NAME_LEN (120)
#define BLE_OTS_OBJ_TYPE_LEN (16)
#define BLE_OTS_OBJ_SIZE_LEN (8)
#define BLE_OTS_OBJ_FIRST_CREATED_LEN (7)
#define BLE_OTS_OBJ_LAST_MODIFIED_LEN (7)
#define BLE_OTS_OBJ_ID_LEN (6)
#define BLE_OTS_OBJ_PROP_LEN (4)
#define BLE_OTS_OBJ_ACTION_CP_LEN (21)
#define BLE_OTS_OBJ_ACTION_CP_CLI_CNFG_LEN (2)
#define BLE_OTS_OBJ_LIST_CP_LEN (7)
#define BLE_OTS_OBJ_LIST_CP_CLI_CNFG_LEN (2)
#define BLE_OTS_OBJ_LIST_FILTER_0_LEN (100)
#define BLE_OTS_OBJ_LIST_FILTER_1_LEN (100)
#define BLE_OTS_OBJ_LIST_FILTER_2_LEN (100)
#define BLE_OTS_OBJ_CHANGED_LEN (7)
#define BLE_OTS_OBJ_CHANGED_CLI_CNFG_LEN (2)

#endif /* GATT_DB_H */