/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
* other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
* EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
* SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS
* SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
* this software. By using this software, you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2019-2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "profile_cmn/r_ble_serv_common.h"

extern st_ble_gatts_db_cfg_t g_gatt_db_table;

typedef enum
{
    BLE_INVALID_ATTR_HDL = 0x0000,
    BLE_GAPS_DECL_HDL = 0x0001,
    BLE_GAPS_DEV_NAME_DECL_HDL = 0x0002,
    BLE_GAPS_DEV_NAME_VAL_HDL = 0x0003,
    BLE_GAPS_APPEARANCE_DECL_HDL = 0x0004,
    BLE_GAPS_APPEARANCE_VAL_HDL = 0x0005,
    BLE_GAPS_PER_PREF_CONN_PARAM_DECL_HDL = 0x0006,
    BLE_GAPS_PER_PREF_CONN_PARAM_VAL_HDL = 0x0007,
    BLE_GAPS_CENT_ADDR_RSLV_DECL_HDL = 0x0008,
    BLE_GAPS_CENT_ADDR_RSLV_VAL_HDL = 0x0009,
    BLE_GAPS_RSLV_PRIV_ADDR_ONLY_DECL_HDL = 0x000A,
    BLE_GAPS_RSLV_PRIV_ADDR_ONLY_VAL_HDL = 0x000B,
    BLE_GATS_DECL_HDL = 0x000C,
    BLE_GATS_SERV_CHGED_DECL_HDL = 0x000D,
    BLE_GATS_SERV_CHGED_VAL_HDL = 0x000E,
    BLE_GATS_SERV_CHGED_CLI_CNFG_DESC_HDL = 0x000F,
    BLE_LSS_DECL_HDL = 0x0010,
    BLE_LSS_SWITCH_STATE_DECL_HDL = 0x0011,
    BLE_LSS_SWITCH_STATE_VAL_HDL = 0x0012,
    BLE_LSS_SWITCH_STATE_CLI_CNFG_DESC_HDL = 0x0013,
    BLE_LSS_BLINK_RATE_DECL_HDL = 0x0014,
    BLE_LSS_BLINK_RATE_VAL_HDL = 0x0015,
    BLE_HRS_DECL_HDL = 0x0016,
    BLE_HRS_MEAS_DECL_HDL = 0x0017,
    BLE_HRS_MEAS_VAL_HDL = 0x0018,
    BLE_HRS_MEAS_CLI_CNFG_DESC_HDL = 0x0019,
    BLE_HRS_BODY_SENSOR_LOCATION_DECL_HDL = 0x001A,
    BLE_HRS_BODY_SENSOR_LOCATION_VAL_HDL = 0x001B,
    BLE_HRS_HEART_RATE_CP_DECL_HDL = 0x001C,
    BLE_HRS_HEART_RATE_CP_VAL_HDL = 0x001D,
    BLE_OTS_DECL_HDL = 0x001E,
    BLE_OTS_FEAT_DECL_HDL = 0x001F,
    BLE_OTS_FEAT_VAL_HDL = 0x0020,
    BLE_OTS_OBJ_NAME_DECL_HDL = 0x0021,
    BLE_OTS_OBJ_NAME_VAL_HDL = 0x0022,
    BLE_OTS_OBJ_TYPE_DECL_HDL = 0x0023,
    BLE_OTS_OBJ_TYPE_VAL_HDL = 0x0024,
    BLE_OTS_OBJ_SIZE_DECL_HDL = 0x0025,
    BLE_OTS_OBJ_SIZE_VAL_HDL = 0x0026,
    BLE_OTS_OBJ_FIRST_CREATED_DECL_HDL = 0x0027,
    BLE_OTS_OBJ_FIRST_CREATED_VAL_HDL = 0x0028,
    BLE_OTS_OBJ_LAST_MODIFIED_DECL_HDL = 0x0029,
    BLE_OTS_OBJ_LAST_MODIFIED_VAL_HDL = 0x002A,
    BLE_OTS_OBJ_ID_DECL_HDL = 0x002B,
    BLE_OTS_OBJ_ID_VAL_HDL = 0x002C,
    BLE_OTS_OBJ_PROP_DECL_HDL = 0x002D,
    BLE_OTS_OBJ_PROP_VAL_HDL = 0x002E,
    BLE_OTS_OBJ_ACTION_CP_DECL_HDL = 0x002F,
    BLE_OTS_OBJ_ACTION_CP_VAL_HDL = 0x0030,
    BLE_OTS_OBJ_ACTION_CP_CLI_CNFG_DESC_HDL = 0x0031,
    BLE_OTS_OBJ_LIST_CP_DECL_HDL = 0x0032,
    BLE_OTS_OBJ_LIST_CP_VAL_HDL = 0x0033,
    BLE_OTS_OBJ_LIST_CP_CLI_CNFG_DESC_HDL = 0x0034,
    BLE_OTS_OBJ_LIST_FILTER_0_DECL_HDL = 0x0035,
    BLE_OTS_OBJ_LIST_FILTER_0_VAL_HDL = 0x0036,
    BLE_OTS_OBJ_LIST_FILTER_1_DECL_HDL = 0x0037,
    BLE_OTS_OBJ_LIST_FILTER_1_VAL_HDL = 0x0038,
    BLE_OTS_OBJ_LIST_FILTER_2_DECL_HDL = 0x0039,
    BLE_OTS_OBJ_LIST_FILTER_2_VAL_HDL = 0x003A,
    BLE_OTS_OBJ_CHANGED_DECL_HDL = 0x003B,
    BLE_OTS_OBJ_CHANGED_VAL_HDL = 0x003C,
    BLE_OTS_OBJ_CHANGED_CLI_CNFG_DESC_HDL = 0x003D,
} e_ble_attr_hdl_t;

#define BLE_GAPS_DEV_NAME_LEN (128)
#define BLE_GAPS_APPEARANCE_LEN (2)
#define BLE_GAPS_PER_PREF_CONN_PARAM_LEN (8)
#define BLE_GAPS_CENT_ADDR_RSLV_LEN (1)
#define BLE_GAPS_RSLV_PRIV_ADDR_ONLY_LEN (1)
#define BLE_GATS_SERV_CHGED_LEN (4)
#define BLE_GATS_SERV_CHGED_CLI_CNFG_LEN (2)
#define BLE_LSS_SWITCH_STATE_LEN (1)
#define BLE_LSS_SWITCH_STATE_CLI_CNFG_LEN (2)
#define BLE_LSS_BLINK_RATE_LEN (1)
#define BLE_HRS_MEAS_LEN (20)
#define BLE_HRS_MEAS_CLI_CNFG_LEN (2)
#define BLE_HRS_BODY_SENSOR_LOCATION_LEN (1)
#define BLE_HRS_HEART_RATE_CP_LEN (1)
#define BLE_OTS_FEAT_LEN (8)
#define BLE_OTS_OBJ_NAME_LEN (512)
#define BLE_OTS_OBJ_TYPE_LEN (16)
#define BLE_OTS_OBJ_SIZE_LEN (8)
#define BLE_OTS_OBJ_FIRST_CREATED_LEN (512)
#define BLE_OTS_OBJ_LAST_MODIFIED_LEN (7)
#define BLE_OTS_OBJ_ID_LEN (6)
#define BLE_OTS_OBJ_PROP_LEN (4)
#define BLE_OTS_OBJ_ACTION_CP_LEN (21)
#define BLE_OTS_OBJ_ACTION_CP_CLI_CNFG_LEN (2)
#define BLE_OTS_OBJ_LIST_CP_LEN (512)
#define BLE_OTS_OBJ_LIST_CP_CLI_CNFG_LEN (2)
#define BLE_OTS_OBJ_LIST_FILTER_0_LEN (100)
#define BLE_OTS_OBJ_LIST_FILTER_1_LEN (100)
#define BLE_OTS_OBJ_LIST_FILTER_2_LEN (100)
#define BLE_OTS_OBJ_CHANGED_LEN (7)
#define BLE_OTS_OBJ_CHANGED_CLI_CNFG_LEN (2)

#endif /* GATT_DB_H */